images:
  # It define the foundational images from Dockerhub
  busybox:
    "1.36":
      persistent_labels:
        created_at: "{{ .DateRFC3339Nano }}"

  base:
    busybox-1.36:
      registry: registry.stevedore.test
      builder:
        driver: docker
        options:
          context:
            - path: images-src/base
      parents:
        busybox:
          - "1.36"
